### ISSUE TITLE
Potential crash when opening window from bottom sheet

### ISSUE THREAD

**Issue by hansemannn** [hansemannn/titanium-bottom-sheet#1]
The app can crash when opening a window from the bottom sheet. This is always reproducible when using the `Don't keep Activities` developer setting on Android. Example:
```js
import TiBottomSheet from 'ti.bottomsheet';

const window = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

const btn = Ti.UI.createButton({ title: 'Show bottom sheet' });
btn.addEventListener('click', () => {
    const contentView = Ti.UI.createView({ height: 200 });
    const innerBtn = Ti.UI.createButton({ title: 'Open Sub Window' });
    innerBtn.addEventListener('click', openSubWindow);

    contentView.add(innerBtn);

    const sheet = TiBottomSheet.createDialog({
        view: contentView,
        cancelable: true,
        sheetState: TiBottomSheet.SHEET_STATE_EXPANDED,
        backgroundColor: 'red',
        canceledOnTouchOutside: true
    });
    sheet.show();
});

window.add(btn);
window.open();

function openSubWindow() {
    const window = Ti.UI.createWindow({ title: 'Sub Window' });
    window.open();
}
```

The error is:
```
[ERROR] WindowManager: android.view.WindowLeaked: Activity org.appcelerator.titanium.TiActivity has leaked window DecorView@9a4bac5[TiActivity] that was originally added here
[ERROR] WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:900)
[ERROR] WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:884)
[ERROR] WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:386)
[ERROR] WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
[ERROR] WindowManager: 	at android.app.Dialog.show(Dialog.java:352) <----
[ERROR] WindowManager: 	at ti.bottomsheet.DialogProxy.show(DialogProxy.kt:99)
[ERROR] WindowManager: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] WindowManager: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[ERROR] WindowManager: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:985)
[ERROR] WindowManager: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1219)
[ERROR] WindowManager: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:261)
[ERROR] WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
[ERROR] WindowManager: 	at android.os.Looper.loop(Looper.java:288)
[ERROR] WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
[ERROR] WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[ERROR] WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by hansemannn** [comment]
cc @prashantsaini1 @m1ga as we talked about it

**Comment by prashantsaini1** [comment]
I was checking this issue and found that since the activity, on which BSD is attached, will be destroyed by OS because of that Developer Setting, is not able to be GC.

I also tried setting a WeakReference but that didn't work too since the activity is not having any strong references at first place.

I couldn't find a way to programmatically detach the activity reference from this BSD before its activity is actually destroyed.

**So as a temporary fix, I tried hiding the BSD and opened a new Ti Window in its close event and it worked properly.**

```
import TiBottomSheet from 'ti.bottomsheet';
let sheet;

(function () {
    $.index.open();
}());

function openSubWindow() {    
    const window = Ti.UI.createWindow({ title: 'Sub Window' });
    window.addEventListener('click', () => window.close() );
    window.open();
}

function createCustomView() {
    const contentView = Ti.UI.createView();
    const innerBtn = Ti.UI.createButton({ title: 'Open Sub Window', height: 200 });
    innerBtn.addEventListener('click', () => sheet.hide());
    contentView.add(innerBtn);
    return contentView;
}

function showSheet(e) {
    sheet = TiBottomSheet.createDialog({
        view: createCustomView(),
        cancelable: true,
        sheetState: TiBottomSheet.SHEET_STATE_EXPANDED,
        backgroundColor: 'red',
        canceledOnTouchOutside: true
    });
    
    sheet.addEventListener('close', () => {
        openSubWindow();    // it works fine since this Dialog will release its references to the activity internally
    });
    
    sheet.show();
}
```

As a permanent fix, I have been reviewing the TiUIAlertDialog code and it's also using some sort of wrapper class to manage the activity references. I will post the permanent solution once it's ready.

**Comment by hansemannn** [comment]
Unfortunately this will not be a feasible solution, as we need to retain the sheet state and want to prevent additional transitions up/down every time a new window is opened. A permanent solution therefore sounds good.

**Comment by m1ga** [comment]
It's strange. Not seeing a crash on my test devices: Pixel 7 (Android 13) and Samsung A20 (Android 11). But only did a quick test run. Sounds like @prashantsaini1 already did some more debugging here and can produce it :+1: Hopefully the TiUIAlertDialog way does the trick!

Even if I attach leakCanary I only see a notification that 5 elements are still there but it goes away after a short time because they are garbage collected.

And I couldn't compile the module because of an error in https://github.com/hansemannn/titanium-bottom-sheet/blob/master/android/src/ti/bottomsheet/DialogProxy.kt#L83 :thinking: had to change it to `titaniumView?.outerView?.let { nestedScrollView!!.addView(it) }`

**Comment by hansemannn** [comment]
Maybe a newer Kotlin version? Thats possible!

**Comment by prashantsaini1** [comment]
@m1ga @hansemannn The compile error was because of null safe check on outerview, so that's absolutely fine at your end.

I also found that the app was not crashing, but I was only getting the Window leakage error on console.

I'm still doing some more tests on TiUIAlertDialog as it seems to be working fine, only that it doesn't show up when the new window is opened because of its actual parent window is destroyed under this setting and all the attached dialogs are destroyed too.

@m1ga if you get some time today, can you check whether it's leaking window even after passing the App Root Activity or Application Context, rather than current activity context in [BottomSheetDialog()](https://github.com/hansemannn/titanium-bottom-sheet/blob/4c7283725b13e9a36728e432fb7d8f549419424b/android/src/ti/bottomsheet/DialogProxy.kt#L38) here?

I'll try the same tomorrow before moving to AlertDialog way.

**Comment by m1ga** [comment]
not even seeing it in the logs:

https://user-images.githubusercontent.com/4334997/207930110-f22d1680-d54f-4d9a-a358-31e0b63bfe9c.mp4

* Module 1.0.0 (that one from the sample folder) and just tested 1.1.0 (from release)
* Ti 11.1.1, 12.0.0.RC
* Pixel 7
* Android 13
* Background limit: none

**Comment by hansemannn** [comment]
Do you have `Don't keep Activities` enabled?

**Comment by m1ga** [comment]
my bad! I've changed the setting below that :man_facepalming: 
Will test it tomorrow again

**Comment by m1ga** [comment]
Now I see it too :smile: 

@prashantsaini1 the Alertdialog part is interesting. There are even some notes about memory leaks: 

https://github.com/tidev/titanium_mobile/blob/f80e1dc35b7e1d8795fd096db2b350fddc94e88c/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDialog.java#L354-L369

just added two buttons to test both ways:
```js
import TiBottomSheet from 'ti.bottomsheet';

const window = Ti.UI.createWindow();

const btn = Ti.UI.createButton({title: 'Show dialog'});
btn.addEventListener('click', () => {
	const contentView = Ti.UI.createView({ height: 200 });
	const innerBtn = Ti.UI.createButton({ title: 'Open Sub Window' });
	innerBtn.addEventListener('click', openSubWindow);

	contentView.add(innerBtn);

	var dialog = Ti.UI.createAlertDialog({
		androidView: contentView
	});
	dialog.show();
});

const btn2 = Ti.UI.createButton({ bottom: 10, title: 'Show bottom sheet'});
btn2.addEventListener('click', () => {
  const contentView = Ti.UI.createView({ height: 200 });
    const innerBtn = Ti.UI.createButton({ title: 'Open Sub Window' });
    innerBtn.addEventListener('click', openSubWindow);

    contentView.add(innerBtn);

    const sheet = TiBottomSheet.createDialog({
        view: contentView,
        cancelable: true,
        sheetState: TiBottomSheet.SHEET_STATE_EXPANDED,
        backgroundColor: 'red',
        canceledOnTouchOutside: true
    });
    sheet.show();
});

window.add([btn, btn2]);
window.open();

function openSubWindow() {
	const window = Ti.UI.createWindow({title: 'Sub Window'});
	window.open();
}
```

> can you check whether it's leaking window even after passing the App Root Activity or Application Context, rather than current activity context in [BottomSheetDialog()](https://github.com/hansemannn/titanium-bottom-sheet/blob/4c7283725b13e9a36728e432fb7d8f549419424b/android/src/ti/bottomsheet/DialogProxy.kt#L38) here

I've tried:
```js
TiApplication.getAppCurrentActivity()
TiApplication.getAppRootOrCurrentActivity()
TiApplication.getInstance().currentActivity
```
but no difference.

https://stackoverflow.com/a/65593461/5193915 same in native land. 
Tried to override `onDestroy` and clean up some parts in there but its not called .

**Comment by prashantsaini1** [comment]
@m1ga I tried the application context as well but same leakage.

Looks like the AlertDialog is the only way, though I've made the changes in the new AlertDialog based class for BSD, but it'll take upto next week as I'm off on this weekend.

@hansemannn fyi

**Comment by hansemannn** [comment]
To be clear here: I am not concerned about the minor leak, it's more that the dialog cannot retain it's state and closes itself / crashes sometimes.

**Comment by prashantsaini1** [comment]
@hansemannn not sure if state can be maintained internally as it's not even happening with the AlertDialog.

**Comment by hansemannn** [comment]
It is retained when "Don't keep activities" is disabled (normal use case). We're doing that in dozens of cases with success. It's just not able to create the state in this module. In our other bottom sheet module that's used for the waypoints map, it's working great. Maybe we should fix this internally @janvennemann

**Comment by prashantsaini1** [comment]
I am able to reproduce the `window-leak (android.view.WindowLeaked)` issue with/without `Don't keep activities`.
- Though it's very uncommon that it'll happen automatically as apps can always handle these cases but since we do it for the `AlertDialog` internally in SDK, I am working upon a permanent solution to this `bottom-sheet-dialog` as well and hoping to bring it in next week.

Also, I confirm that an `AlertDialog` is not retained if `Don't keep activities` is enabled.
- The reason is that a Dialog (AlertDialog or BottomSheetDialog or native ProgressDialog) contains its hosting activity reference, and if it's supposed to be retained after the activity is destroyed and recreated, then it won't let go off its hosting activity reference during destroy and thus ends up creating a memory leak anyways.
- Native apps probably do this by storing a boolean flag before the activity is destroyed and re-show the dialog after reading the stored boolean from activity lifecycle bundle. Doing so, native apps releases their dialog and avoid storing its activity reference.

I will still check further if the native apps approach can be applied in Titanium SDK as well but I believe it's not a higher priority than the `window-leak` fix.

**Comment by prashantsaini1** [comment]
[Fixed here](https://github.com/hansemannn/titanium-bottom-sheet/commit/9195fb7072ec08dc7a316db38059120a3d74f616)
1. The Bottom Sheet Dialog (BSD) is now able to hide without any crashes or memory leaks. It will automatically hide when its hosting ti-window is closed.
2. The BSD `close` event is now always guaranteed to be called even with `Don't keep activities ON` so apps can now do further processing more reliably.
3. This fix is backed by [another fix in SDK in this PR](https://github.com/tidev/titanium-sdk/pull/14189).

**Comment by prashantsaini1** [comment]
[Fixed here](https://github.com/hansemannn/titanium-bottom-sheet/commit/9195fb7072ec08dc7a316db38059120a3d74f616)

**Comment by hansemannn** [comment]
Thanks!
